import { Course } from '@/features/courses/interfaces/course'

export const COURSE_CATALOG: Course[] = [
  {
    code: 'WR 121',
    subject: 'WR',
    number: '121',
    title: 'Composition I',
    credits: 3,
    description: 'Foundations of academic writing.',
    offeredTerms: ['Fall', 'Winter', 'Spring', 'Summer'],
  },
  {
    code: 'MTH 111',
    subject: 'MTH',
    number: '111',
    title: 'College Algebra',
    credits: 4,
    description: 'Functions, equations, and algebraic modeling.',
    offeredTerms: ['Fall', 'Winter', 'Spring', 'Summer'],
  },
  {
    code: 'MTH 112',
    subject: 'MTH',
    number: '112',
    title: 'Elementary Functions',
    credits: 4,
    description: 'Exponential, logarithmic, and trigonometric functions.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'MTH 111',
    prerequisiteRule: {
      allOf: ['MTH 111'],
    },
  },
  {
    code: 'MTH 231',
    subject: 'MTH',
    number: '231',
    title: 'Differential Calculus',
    credits: 4,
    description: 'Limits, derivatives, and applications.',
    offeredTerms: ['Fall', 'Winter', 'Spring', 'Summer'],
    prerequisiteText: 'MTH 112',
    prerequisiteRule: {
      allOf: ['MTH 112'],
    },
  },
  {
    code: 'CS 160',
    subject: 'CS',
    number: '160',
    title: 'Introduction to Computer Science Orientation',
    credits: 1,
    description: 'Orientation to the CS program and professional practices.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
  },
  {
    code: 'CS 161',
    subject: 'CS',
    number: '161',
    title: 'Introduction to Computer Science I',
    credits: 4,
    description: 'Programming fundamentals and algorithmic thinking.',
    offeredTerms: ['Fall', 'Winter', 'Spring', 'Summer'],
  },
  {
    code: 'CS 162',
    subject: 'CS',
    number: '162',
    title: 'Introduction to Computer Science II',
    credits: 4,
    description: 'Object-oriented design and software engineering basics.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 161',
    prerequisiteRule: {
      allOf: ['CS 161'],
    },
  },
  {
    code: 'CS 225',
    subject: 'CS',
    number: '225',
    title: 'Discrete Structures in Computer Science',
    credits: 4,
    description: 'Logic, sets, proof techniques, and combinatorics.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 161 and MTH 111',
    prerequisiteRule: {
      allOf: ['CS 161', 'MTH 111'],
    },
  },
  {
    code: 'CS 261',
    subject: 'CS',
    number: '261',
    title: 'Data Structures',
    credits: 4,
    description: 'Lists, trees, graphs, and runtime analysis.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 162',
    prerequisiteRule: {
      allOf: ['CS 162'],
    },
  },
  {
    code: 'CS 271',
    subject: 'CS',
    number: '271',
    title: 'Computer Architecture and Assembly Language',
    credits: 4,
    description: 'Computer organization and low-level programming.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 161 and MTH 111',
    prerequisiteRule: {
      allOf: ['CS 161', 'MTH 111'],
    },
  },
  {
    code: 'CS 290',
    subject: 'CS',
    number: '290',
    title: 'Web Development',
    credits: 4,
    description: 'Client/server web applications and APIs.',
    offeredTerms: ['Fall', 'Winter', 'Spring', 'Summer'],
    prerequisiteText: 'CS 162',
    prerequisiteRule: {
      allOf: ['CS 162'],
    },
  },
  {
    code: 'CS 325',
    subject: 'CS',
    number: '325',
    title: 'Analysis of Algorithms',
    credits: 4,
    description: 'Algorithm design, complexity, and correctness proofs.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 261 and MTH 231',
    prerequisiteRule: {
      allOf: ['CS 261', 'MTH 231'],
    },
  },
  {
    code: 'CS 340',
    subject: 'CS',
    number: '340',
    title: 'Introduction to Databases',
    credits: 4,
    description: 'Relational models, SQL, and schema design.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 261 and one of (CS 290, CS 271)',
    prerequisiteRule: {
      allOf: ['CS 261'],
      oneOf: ['CS 290', 'CS 271'],
    },
  },
  {
    code: 'CS 344',
    subject: 'CS',
    number: '344',
    title: 'Operating Systems I',
    credits: 4,
    description: 'Processes, memory, synchronization, and file systems.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 261',
    prerequisiteRule: {
      allOf: ['CS 261'],
    },
  },
  {
    code: 'CS 361',
    subject: 'CS',
    number: '361',
    title: 'Software Engineering I',
    credits: 4,
    description: 'Software process, collaboration, and project architecture.',
    offeredTerms: ['Fall', 'Winter', 'Spring'],
    prerequisiteText: 'CS 261 and CS 290',
    prerequisiteRule: {
      allOf: ['CS 261', 'CS 290'],
    },
  },
  {
    code: 'CS 362',
    subject: 'CS',
    number: '362',
    title: 'Software Engineering II',
    credits: 4,
    description: 'Team software engineering with QA and deployment focus.',
    offeredTerms: ['Winter', 'Spring'],
    prerequisiteText: 'CS 361',
    prerequisiteRule: {
      allOf: ['CS 361'],
    },
  },
  {
    code: 'CS 381',
    subject: 'CS',
    number: '381',
    title: 'Programming Language Fundamentals',
    credits: 4,
    description: 'Language design, interpreters, and semantics.',
    offeredTerms: ['Fall'],
    prerequisiteText:
      'CS 261 and (MTH 231 or equivalent placement); additional department conditions may apply.',
    requiresManualCheck: true,
  },
]

export const COURSE_MAP = new Map(COURSE_CATALOG.map(course => [course.code, course]))

export function listCourseSubjects() {
  return Array.from(new Set(COURSE_CATALOG.map(course => course.subject))).sort((a, b) =>
    a.localeCompare(b)
  )
}
